<a href="https://colab.research.google.com/github/logeshpalanivel/SVM_Gender_classification/blob/main/SVM_Gender_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv("/content/gender_classification_v7.csv")

In [5]:
df.head()

long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0          1               11.8                 6.1          1          0   
1          0               14.0                 5.4          0          0   
2          0               11.8                 6.3          1          1   
3          0               14.4                 6.1          0          1   
4          1               13.5                 5.9          0          0   

   lips_thin  distance_nose_to_lip_long  gender  
0          1                          1    Male  
1          1                          0  Female  
2          1                          1    Male  
3          1                          1    Male  
4          0                          0  Female

In [6]:
df.tail()

long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
4996          1               13.6                 5.1          0          0   
4997          1               11.9                 5.4          0          0   
4998          1               12.9                 5.7          0          0   
4999          1               13.2                 6.2          0          0   
5000          1               15.4                 5.4          1          1   

      lips_thin  distance_nose_to_lip_long  gender  
4996          0                          0  Female  
4997          0                          0  Female  
4998          0                          0  Female  
4999          0                          0  Female  
5000          1                          1    Male

In [7]:
df.describe()

long_hair  forehead_width_cm  forehead_height_cm    nose_wide  \
count  5001.000000        5001.000000         5001.000000  5001.000000   
mean      0.869626          13.181484            5.946311     0.493901   
std       0.336748           1.107128            0.541268     0.500013   
min       0.000000          11.400000            5.100000     0.000000   
25%       1.000000          12.200000            5.500000     0.000000   
50%       1.000000          13.100000            5.900000     0.000000   
75%       1.000000          14.000000            6.400000     1.000000   
max       1.000000          15.500000            7.100000     1.000000   

         nose_long    lips_thin  distance_nose_to_lip_long  
count  5001.000000  5001.000000                5001.000000  
mean      0.507898     0.493101                   0.498900  
std       0.499988     0.500002                   0.500049  
min       0.000000     0.000000                   0.000000  
25%       0.000000     0.000000                   0.000000  
50%       1.000000     0.000000                   0.000000  
75%       1.000000     1.000000                   1.000000  
max       1.000000     1.000000                   1.000000

In [8]:
df.shape

(5001, 8)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5001 entries, 0 to 5000
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   long_hair                  5001 non-null   int64  
 1   forehead_width_cm          5001 non-null   float64
 2   forehead_height_cm         5001 non-null   float64
 3   nose_wide                  5001 non-null   int64  
 4   nose_long                  5001 non-null   int64  
 5   lips_thin                  5001 non-null   int64  
 6   distance_nose_to_lip_long  5001 non-null   int64  
 7   gender                     5001 non-null   object 
dtypes: float64(2), int64(5), object(1)
memory usage: 312.7+ KB


In [10]:
df.isnull().sum()

long_hair                    0
forehead_width_cm            0
forehead_height_cm           0
nose_wide                    0
nose_long                    0
lips_thin                    0
distance_nose_to_lip_long    0
gender                       0
dtype: int64

In [11]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
df['gender'] = le.fit_transform(df['gender'])

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5001 entries, 0 to 5000
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   long_hair                  5001 non-null   int64  
 1   forehead_width_cm          5001 non-null   float64
 2   forehead_height_cm         5001 non-null   float64
 3   nose_wide                  5001 non-null   int64  
 4   nose_long                  5001 non-null   int64  
 5   lips_thin                  5001 non-null   int64  
 6   distance_nose_to_lip_long  5001 non-null   int64  
 7   gender                     5001 non-null   int64  
dtypes: float64(2), int64(6)
memory usage: 312.7 KB


In [13]:
X = df.drop('gender',axis=1)
Y = df['gender']


In [14]:
X

long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0             1               11.8                 6.1          1          0   
1             0               14.0                 5.4          0          0   
2             0               11.8                 6.3          1          1   
3             0               14.4                 6.1          0          1   
4             1               13.5                 5.9          0          0   
...         ...                ...                 ...        ...        ...   
4996          1               13.6                 5.1          0          0   
4997          1               11.9                 5.4          0          0   
4998          1               12.9                 5.7          0          0   
4999          1               13.2                 6.2          0          0   
5000          1               15.4                 5.4          1          1   

      lips_thin  distance_nose_to_lip_long  
0             1                          1  
1             1                          0  
2             1                          1  
3             1                          1  
4             0                          0  
...         ...                        ...  
4996          0                          0  
4997          0                          0  
4998          0                          0  
4999          0                          0  
5000          1                          1  

[5001 rows x 7 columns]

In [15]:
Y

0       1
1       0
2       1
3       1
4       0
       ..
4996    0
4997    0
4998    0
4999    0
5000    1
Name: gender, Length: 5001, dtype: int64

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.25,random_state=0)

In [17]:
x_train.shape

(3750, 7)

In [18]:
x_test.shape

(1251, 7)

In [19]:
from sklearn.preprocessing import StandardScaler
c=StandardScaler()
x_train = c.fit_transform(x_train)

In [20]:
x_train

array([[ 0.39404064,  0.73932618, -1.54246808, ..., -1.01884419,
        -0.9883347 , -1.0101852 ],
       [ 0.39404064, -1.06057202,  0.84052412, ..., -1.01884419,
        -0.9883347 , -1.0101852 ],
       [ 0.39404064,  0.19935672,  0.84052412, ...,  0.98150435,
        -0.9883347 ,  0.98991749],
       ...,
       [ 0.39404064,  1.00931091,  0.47390994, ...,  0.98150435,
        -0.9883347 , -1.0101852 ],
       [-2.53780933, -1.06057202,  1.57375249, ...,  0.98150435,
         1.01180298,  0.98991749],
       [ 0.39404064,  1.00931091, -0.44262553, ..., -1.01884419,
        -0.9883347 , -1.0101852 ]])

In [21]:
from sklearn.svm import SVC
clf = SVC(kernel='linear')

In [22]:
clf.fit(x_train,y_train)

SVC(kernel='linear')

In [23]:
y_pred = clf.predict(x_test)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(


In [24]:
y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [25]:
from sklearn.metrics import accuracy_score
a = accuracy_score(y_pred , y_test)
a

0.486810551558753

In [26]:
from sklearn.metrics import confusion_matrix
c= confusion_matrix(y_pred,y_test)
c

array([[  0,   0],
       [642, 609]])